# Generated by Django 3.1 on 2021-06-11 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_auto_20210611_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='duration',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
