# Generated by Django 3.1 on 2021-06-11 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
